# Generated by Django 5.0.4 on 2024-04-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_loginhistoryentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginhistory',
            old_name='login_time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='registerhistory',
            old_name='registration_time',
            new_name='timestamp',
        ),
        migrations.DeleteModel(
            name='LoginHistoryEntry',
        ),
    ]
